// src_PIQ-StudentTemplate_csv

let
  Source = SharePoint.Files("https://tamucs.sharepoint.com/teams/Team-vcom-oat-vdata-dev", [ApiVersion = 15]),
  Navigation = Source{[Name = "PIQ_StudentTemplate.csv", #"Folder Path" = "https://tamucs.sharepoint.com/teams/Team-vcom-oat-vdata-dev/datafiles/inbound/"]}[Content],
  #"Imported CSV" = Csv.Document(Navigation, [Delimiter = ",", Columns = 25, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
  #"Cleaned text" = Table.TransformColumns(#"Imported CSV", {{"Column1", each Text.Clean(_), type nullable text}, {"Column2", each Text.Clean(_), type nullable text}, {"Column3", each Text.Clean(_), type nullable text}, {"Column4", each Text.Clean(_), type nullable text}, {"Column5", each Text.Clean(_), type nullable text}, {"Column6", each Text.Clean(_), type nullable text}, {"Column7", each Text.Clean(_), type nullable text}, {"Column8", each Text.Clean(_), type nullable text}, {"Column9", each Text.Clean(_), type nullable text}, {"Column10", each Text.Clean(_), type nullable text}, {"Column11", each Text.Clean(_), type nullable text}, {"Column12", each Text.Clean(_), type nullable text}, {"Column13", each Text.Clean(_), type nullable text}, {"Column14", each Text.Clean(_), type nullable text}, {"Column15", each Text.Clean(_), type nullable text}, {"Column16", each Text.Clean(_), type nullable text}, {"Column17", each Text.Clean(_), type nullable text}, {"Column18", each Text.Clean(_), type nullable text}, {"Column19", each Text.Clean(_), type nullable text}, {"Column20", each Text.Clean(_), type nullable text}, {"Column21", each Text.Clean(_), type nullable text}, {"Column22", each Text.Clean(_), type nullable text}, {"Column23", each Text.Clean(_), type nullable text}, {"Column24", each Text.Clean(_), type nullable text}, {"Column25", each Text.Clean(_), type nullable text}}),
  #"Trimmed text" = Table.TransformColumns(#"Cleaned text", {{"Column1", each Text.Trim(_), type nullable text}, {"Column2", each Text.Trim(_), type nullable text}, {"Column3", each Text.Trim(_), type nullable text}, {"Column4", each Text.Trim(_), type nullable text}, {"Column5", each Text.Trim(_), type nullable text}, {"Column6", each Text.Trim(_), type nullable text}, {"Column7", each Text.Trim(_), type nullable text}, {"Column8", each Text.Trim(_), type nullable text}, {"Column9", each Text.Trim(_), type nullable text}, {"Column10", each Text.Trim(_), type nullable text}, {"Column11", each Text.Trim(_), type nullable text}, {"Column12", each Text.Trim(_), type nullable text}, {"Column13", each Text.Trim(_), type nullable text}, {"Column14", each Text.Trim(_), type nullable text}, {"Column15", each Text.Trim(_), type nullable text}, {"Column16", each Text.Trim(_), type nullable text}, {"Column17", each Text.Trim(_), type nullable text}, {"Column18", each Text.Trim(_), type nullable text}, {"Column19", each Text.Trim(_), type nullable text}, {"Column20", each Text.Trim(_), type nullable text}, {"Column21", each Text.Trim(_), type nullable text}, {"Column22", each Text.Trim(_), type nullable text}, {"Column23", each Text.Trim(_), type nullable text}, {"Column24", each Text.Trim(_), type nullable text}, {"Column25", each Text.Trim(_), type nullable text}}),
  #"Promoted headers" = Table.PromoteHeaders(#"Trimmed text", [PromoteAllScalars = true]),
  #"Select all ACTIVE" = Table.SelectRows(#"Promoted headers", each ([#"Account(Active/Inactive)"] = "Active")),
  #"Removed columns" = Table.RemoveColumns(#"Select all ACTIVE", {"DOB", "Gender", "GenderIdentity", "Race", "Ethnicity"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "piq_account_active", each true), {{"piq_account_active", type logical}}),
  #"Inserted conditional column" = Table.AddColumn(#"Added custom", "piq_DegreeConferred_tf", each if [DegreeConferredDate] = "1900-01-01" then false else true),
  #"Changed column type" = Table.TransformColumnTypes(#"Inserted conditional column", {{"piq_DegreeConferred_tf", type logical}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Changed column type", {"AnticipatedGraduationDate", "DegreeConferredDate"})
in
  #"Removed columns 1"